version: '3.7'

services:
  notes_app_db:
    container_name: "db_test_notes_app"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./database/docker/dev/Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "db_test_notes_app"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
networks:
  default:
volumes:
  mysql_data: