// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewNote struct {
	Text string `json:"text"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type OverviewNote struct {
	ID           int       `json:"id"`
	OverviewText string    `json:"overviewText"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}
