// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"github.com/minhtuhcmus/coder-push-notes-mono-repo/backend/domain/handler"
	"github.com/minhtuhcmus/coder-push-notes-mono-repo/backend/domain/middlewares"
	"github.com/minhtuhcmus/coder-push-notes-mono-repo/backend/domain/repositories"
	"github.com/minhtuhcmus/coder-push-notes-mono-repo/backend/domain/services"
	"net/http"
)

// Injectors from wire.go:

func InitHTTPServer(ctx context.Context) (http.Handler, error) {
	middleware := middlewares.NewMiddleware()
	userRepository := repositories.NewUserRepository()
	authService := services.NewAuthService(userRepository)
	noteRepository := repositories.NewNoteRepository()
	noteService := services.NewNoteService(noteRepository)
	httpHandler := handler.NewHTTPServer(middleware, authService, noteService)
	return httpHandler, nil
}
